# Travis CI configuration file
# http://travis-ci.org

sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks
    - pandoc

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck

# Run luacheck to make sure there is not syntax error left in the add-on
script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

deploy:
  provider: script
  script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 8.2.5 -o
  on:
    tags: true

notifications:
  email:
    on_failure: always
    on_success: never
